kumuluzee:
  name: shopping-cart-service
  version: 1.0.0-SNAPSHOT
  env:
    prod: false
    name: dev
  server:
    show-server-info: false
    base-url: http://localhost:8080
    http:
      port: 8080
  cors-filter:
    servlet:
      allow-origin: "*"
      supported-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS, HEAD"
      exposed-headers: "X-Total-Count"
  openapi:
    enabled: true
    ui:
      enabled: true
  logs:
    config-file: '<?xml version="1.0" encoding="UTF-8"?>
      <Configuration name="shopping-cart-service">
          <Appenders>
              <Console name="console" target="SYSTEM_OUT">
                  <PatternLayout pattern="%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n" />
              </Console>
              <Socket name="logstash" host="2034b16a-d2cd-4921-87d9-b890b8a2b74f-ls.logit.io" port="17244" protocol="tcp">
                  <JSONLayout complete="false" compact="true" eventEol="true" charset="UTF-8" properties="true"/>
              </Socket>
          </Appenders>
          <Loggers>
              <Root level="all">
                  <AppenderRef ref="console" level="info"/>
                  <AppenderRef ref="logstash" level="trace"/>
              </Root>
          </Loggers>
      </Configuration>'
  config:
    consul:
      agent: http://localhost:8500
  discovery:
    cluster: cluster-id
    consul:
      agent: http://localhost:8500
  health:
    servlet:
      mapping: /health/
      enabled: true
    checks:
      data-source-health-check:
        type: liveness
        jndi-name: jdbc/mainDB
      disk-space-health-check:
        threshold: 100000000
        type: liveness
  datasources:
    - jndi-name: jdbc/mainDB
      connection-url: jdbc:postgresql://localhost:5432/shopping-cart-service
      username: postgres
      password: postgres
      pool:
        max-size: 10
  metrics:
    web-instrumentation:
      - name: shopping-cart-endpoint
        url-pattern: /v1/shopping-cart/*
  security:
    keycloak:
      json: '{
               "realm": "rso",
               "bearer-only": true,
               "auth-server-url": "https://keycloak.mjamsek.com/auth",
               "ssl-required": "external",
               "resource": "shopping-cart-service",
               "confidential-port": 0
             }'
