apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-cart-app-deployment
  namespace: e-store
spec:
  selector:
    matchLabels:
      app: shopping-cart-app-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: shopping-cart-app-deployment
    spec:
      containers:
        - name: shopping-cart-app-container
          image: rso6315/shopping-cart-service:latest
          ports:
            - containerPort: 8080
          env:
            - name: KUMULUZEE_DISCOVERY_CLUSTER
              value: second-cluster
            - name: KUMULUZEE_CONFIG_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DISCOVERY_CONSUL_AGENT
              value: http://consul-service-consul-server.e-store:8500
            - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
              value: jdbc:postgresql://shopping-cart-db.e-store:5432/shopping-cart
            - name: KUMULUZEE_DATASOURCES0_USERNAME
              value: postgres
            - name: KUMULUZEE_DATASOURCES0_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: shopping-cart-pass
                  key: POSTGRES_PASSWORD
      #          readinessProbe:
      #            httpGet:
      #              path: /health/live
      #              port: 8082
      #              httpHeaders:
      #                - name: Custom-Header
      #                  value: Awesome
      #            initialDelaySeconds: 3
      #            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shopping-cart-service
  name: shopping-cart-service
  namespace: e-store
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 31018
      targetPort: 8080
      protocol: TCP
  selector:
    app: shopping-cart-app-deployment